name: PR

on:
  pull_request:
    branches:
    - iam

  push:
    branches:
    - iam

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        run: |
            docker login --username=${{ secrets.USERNAME_ALI }} registry.cn-hangzhou.aliyuncs.com -p ${{ secrets.PASSWORD_ALI }}

      - name: build & publish images
        run: |
          REGISTRY=registry.cn-hangzhou.aliyuncs.com/testwydimage ARCHS='amd64 arm64' GOOS=linux VERSION='viam.0.0' make  push-multiarch-images